spring.application.name=baitap
spring.datasource.url=jdbc:mysql://localhost:3307/demospringjpa09 
spring.datasource.username=root
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=none
jwt.secret=AT7/laCq3slIEIC0Fae/Vho00PIND7+uFOM4urWfLPM=
